Repository GLVis/glvis, pull requests merged in 2018-04, with the labels that each got.

#56 Fix the GLVis build when freetype + fontconfig are disabled [freetype-off-fix]
  lib/aux_vis.hpp
  lib/vsdata.cpp
Labels: bug, building, in-next

#57 Attempt to find the proper prefix for X11 from a given list [auto-find-x11]
  makefile
Labels: building, enhancement, in-next

#49 DOI number through DOE Code [doi-dev]
  INSTALL
  README
Labels: documentation
