Repository GLVis/glvis, pull requests merged in 2020-12, with the labels that each got.

#121 Another fix for MPI+X11 error
  lib/gl/platform_gl.hpp
  lib/sdl.cpp
  lib/sdl.hpp
Labels: bug, building

#122 Fix for GLM on LC Intel compilers
  lib/gl/types.hpp
Labels: bug, building

#125 Fix a build issue on Ubuntu
  lib/sdl_x11.hpp
Labels: bug, building

#127 Fix for numpad keys issuing duplicate commands
  lib/sdl.cpp
Labels: bug, usage

#126 move mesh division in 2d to key 'o' for consistency with 3d
  CHANGELOG
  README
  lib/vssolution.cpp
Labels: low-impact, minor, ready-for-review

#115 BSD Relicense
  CHANGELOG
  CMakeLists.txt
  CONTRIBUTING.md
  COPYRIGHT
  LICENSE
  NOTICE
  README
  glvis-keygen.sh
  glvis.cpp
  lib/CMakeLists.txt
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/font.cpp
  lib/font.hpp
  lib/gl/attr_traits.hpp
  lib/gl/platform_gl.hpp
  lib/gl/renderer.cpp
  lib/gl/renderer.hpp
  lib/gl/renderer_core.cpp
  lib/gl/renderer_core.hpp
  lib/gl/renderer_ff.cpp
  lib/gl/renderer_ff.hpp
  lib/gl/shaders/default.frag
  lib/gl/shaders/default.vert
  lib/gl/shaders/lighting.glsl
  lib/gl/shaders/printing.frag
  lib/gl/shaders/printing.vert
  lib/gl/types.cpp
  lib/gl/types.hpp
  lib/logo.hpp
  lib/material.cpp
  lib/material.hpp
  lib/openglvis.cpp
  lib/openglvis.hpp
  lib/palettes.cpp
  lib/palettes.hpp
  lib/sdl.cpp
  lib/sdl.hpp
  lib/sdl_helper.hpp
  lib/sdl_mac.hpp
  lib/sdl_mac.mm
  lib/sdl_x11.hpp
  lib/threads.cpp
  lib/threads.hpp
  lib/visual.hpp
  lib/vsdata.cpp
  lib/vsdata.hpp
  lib/vssolution.cpp
  lib/vssolution.hpp
  lib/vssolution3d.cpp
  lib/vssolution3d.hpp
  lib/vsvector.cpp
  lib/vsvector.hpp
  lib/vsvector3d.cpp
  lib/vsvector3d.hpp
  makefile
  share/CMakeLists.txt
Labels: documentation, high-impact, release

#123 Final changes for glvis-4.0
  CHANGELOG
  CMakeLists.txt
  CONTRIBUTING.md
  README
  glvis.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/font.hpp
  lib/gl/attr_traits.hpp
  lib/gl/platform_gl.hpp
  lib/gl/renderer.cpp
  lib/gl/renderer.hpp
  lib/gl/renderer_core.hpp
  lib/gl/renderer_ff.cpp
  lib/gl/renderer_ff.hpp
  lib/gl/types.cpp
  lib/gl/types.hpp
  lib/gl2ps.c
  lib/logo.hpp
  lib/material.hpp
  lib/openglvis.hpp
  lib/palettes.hpp
  lib/sdl.cpp
  lib/sdl.hpp
  lib/sdl_x11.hpp
  lib/threads.hpp
  lib/visual.hpp
  lib/vsdata.hpp
  lib/vssolution.cpp
  lib/vssolution.hpp
  lib/vssolution3d.cpp
  lib/vssolution3d.hpp
  lib/vsvector.cpp
  lib/vsvector.hpp
  lib/vsvector3d.cpp
  lib/vsvector3d.hpp
  makefile
Labels: release

#130 Refactor glvis main file; fix for segfault on glvis script
  CHANGELOG
  glvis.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/vssolution.cpp
  lib/vssolution3d.cpp
  lib/vsvector.cpp
  lib/vsvector3d.cpp
Labels: bug, enhancement

#134 Fix for texturing in WebGL
  CHANGELOG
  lib/gl/renderer.cpp
  lib/gl/renderer.hpp
  lib/palettes.cpp
Labels: bug

#135 Shared stream reader
  glvis.cpp
  lib/CMakeLists.txt
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/sdl.cpp
  lib/stream_reader.cpp
  lib/stream_reader.hpp
  makefile
Labels: ready-for-review

#136 Emscripten Improvements
  lib/aux_js.cpp
  lib/sdl.cpp
  lib/sdl.hpp
  makefile
Labels: JS, emscripten, enhancement, ready-for-review
