Repository GLVis/glvis, pull requests merged in 2021-04, with the labels that each got.

#164 Introduce automated testing with GitHub Actions
  .github/workflows/builds.yml
Labels: ready-for-review, testing

#167 Build mfem sequential by default, parallel as a bonus
  .github/workflows/builds.yml
Labels: building, ready-for-review

#169 Update INSTALL to describe Mac OS X error workaround
  INSTALL
Labels: bug, documentation, ready-for-review
