Repository GLVis/glvis, pull requests merged in 2021-07, with the labels that each got.

#174 Threaded server/display mode (for real this time)
  CHANGELOG
  CMakeLists.txt
  glvis.cpp
  lib/CMakeLists.txt
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/logo.hpp
  lib/openglvis.hpp
  lib/palettes.cpp
  lib/sdl.cpp
  lib/sdl.hpp
  lib/sdl_helper.cpp
  lib/sdl_helper.hpp
  lib/sdl_mac.hpp
  lib/sdl_mac.mm
  lib/sdl_main.cpp
  lib/sdl_main.hpp
  lib/sdl_x11.cpp
  lib/sdl_x11.hpp
  lib/stream_reader.cpp
  lib/threads.cpp
  lib/threads.hpp
  lib/vsdata.cpp
  lib/vsdata.hpp
  lib/vssolution.cpp
  lib/vssolution3d.cpp
  lib/vsvector.cpp
  lib/vsvector3d.cpp
  makefile
  share/CMakeLists.txt
  share/windows.manifest
Labels: Mac, Windows, ready-for-review

#179 Fix for building with MFEM+gslib
  lib/palettes.cpp
Labels: bug, building

#180 Fix warnings and GnuTLS build
  glvis.cpp
  lib/sdl_mac.mm
  lib/sdl_main.cpp
Labels: building, ready-for-review

#181 Fix style
  lib/sdl_main.cpp
Labels: minor, testing
