Repository GLVis/glvis, pull requests merged in 2021-08, with the labels that each got.

#183 Fix web version link
  makefile
Labels: bug, emscripten, ready-for-review

#185 Fix for live site hang
  lib/sdl.cpp
  lib/sdl_main.cpp
Labels: bug, emscripten

#184 Create Mac application bundle
  .gitignore
  CHANGELOG
  CMakeLists.txt
  INSTALL
  makefile
  share/Credits.rtf
  share/GLVis.icns
  share/Info.plist
Labels: enhancement, Mac

#190 Minor cleanup of thread signaling
  lib/sdl.cpp
  lib/sdl.hpp
  lib/sdl_main.cpp
  lib/sdl_main.hpp
  lib/threads.cpp
  lib/threads.hpp
Labels: minor

#192 Rename Github Actions, needs update of mfem-actions version
  .github/workflows/builds.yml
Labels: minor, testing

#193 Fix style
  CONTRIBUTING.md
  lib/sdl.cpp
  lib/threads.cpp
Labels: documentation

#188 Update numbering when a new mesh and solution is read
  lib/vssolution.cpp
Labels: minor, ready-for-review

#186 Final changes for glvis-4.1
  CHANGELOG
  CONTRIBUTING.md
  INSTALL
  README
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/geom_utils.hpp
  lib/openglvis.cpp
  lib/palettes.cpp
  lib/sdl.cpp
  lib/sdl_main.cpp
  lib/stream_reader.cpp
  lib/stream_reader.hpp
  lib/vsdata.cpp
  lib/vsdata.hpp
  makefile
  tests/glvis_driver.py
Labels: release
