Repository GLVis/glvis, pull requests merged in 2021-02, with the labels that each got.

#151 Add key processing JavaScript callbacks
  lib/aux_js.cpp
  lib/sdl.hpp
Labels: emscripten, enhancement, minor

#156 Pinch to zoom
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/sdl.cpp
  lib/sdl.hpp
Labels: emscripten, enhancement, in-review

#152 Palettes refactor (and some other stuff)
  CHANGELOG
  glvis.cpp
  lib/CMakeLists.txt
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/aux_vis.hpp
  lib/geom_utils.hpp
  lib/gl/renderer.cpp
  lib/gl/renderer.hpp
  lib/gl/renderer_core.cpp
  lib/gl/renderer_core.hpp
  lib/gl/renderer_ff.cpp
  lib/gl/renderer_ff.hpp
  lib/gl/types.hpp
  lib/openglvis.cpp
  lib/openglvis.hpp
  lib/palettes.cpp
  lib/palettes.hpp
  lib/threads.cpp
  lib/vsdata.cpp
  lib/vssolution.cpp
  lib/vssolution.hpp
  lib/vssolution3d.cpp
  lib/vssolution3d.hpp
  lib/vsvector.cpp
  lib/vsvector3d.cpp
  makefile
Labels: enhancement, in-review

#153 StreamState refactor
  glvis.cpp
  lib/aux_js.cpp
  lib/stream_reader.cpp
  lib/stream_reader.hpp
  lib/threads.cpp
  lib/threads.hpp
Labels: enhancement, in-review
