Repository GLVis/glvis, pull requests merged in 2021-01, with the labels that each got.

#142 GetHelpString v2
  lib/aux_js.cpp
  lib/sdl.cpp
  lib/sdl.hpp
  lib/vsdata.cpp
  lib/vsdata.hpp
  lib/vssolution.cpp
  lib/vssolution.hpp
  lib/vssolution3d.cpp
  lib/vssolution3d.hpp
  lib/vsvector.cpp
  lib/vsvector.hpp
  lib/vsvector3d.cpp
  lib/vsvector3d.hpp
Labels: minor, ready-for-review

#138 Fixes for the JS version
  CHANGELOG
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/vssolution.cpp
Labels: JS, bug, minor, ready-for-review

#139 GetHelpString
  lib/aux_js.cpp
  lib/vsdata.cpp
  lib/vsdata.hpp
  lib/vssolution.cpp
  lib/vssolution.hpp
  lib/vssolution3d.cpp
  lib/vssolution3d.hpp
  lib/vsvector.cpp
  lib/vsvector.hpp
  lib/vsvector3d.cpp
  lib/vsvector3d.hpp
Labels: minor, ready-for-review

#137 WebGL 2 support
  CHANGELOG
  CMakeLists.txt
  lib/aux_js.cpp
  lib/aux_vis.cpp
  lib/font.cpp
  lib/gl/renderer.cpp
  lib/gl/renderer.hpp
  lib/gl/renderer_core.cpp
  lib/gl/shaders/default.frag
  lib/gl/shaders/printing.vert
  lib/palettes.cpp
  lib/sdl.cpp
  lib/sdl.hpp
  lib/vssolution.cpp
  makefile
Labels: emscripten, enhancement, ready-for-review

#143 Improved Emscripten Stream Updates
  lib/aux_js.cpp
Labels: emscripten, ready-for-review

#145 CMake build fix for logo
  share/CMakeLists.txt
Labels: bug, building

#146 Fix visualization of 2D meshes
  glvis.cpp
  lib/aux_js.cpp
Labels: bug, high-impact, ready-for-review

#147 Parse the valuerange command in JS streams
  lib/aux_js.cpp
Labels: JS, enhancement, minor
