Repository GLVis/glvis, pull requests merged in 2024-08, with the labels that each got.

#302 Fixed use-after-delete with dynamic streams and switching quadratures
  glvis.cpp
  lib/stream_reader.cpp
  lib/stream_reader.hpp
Labels: bug, in-review

#305 Fix the CMake 'install' target on macOS to sign bundled dependencies.
  .github/workflows/release.yml
  CHANGELOG
  CMakeLists.txt
Labels: building, Mac, ready-for-review

#296 CI misc improvements
  .github/workflows/builds.yml
  CHANGELOG
  tests/CMakeLists.txt
  tests/glvis_driver.py
  tests/requirements.txt
  tests/test_cmd.py
Labels: building, ready-for-review

#310 Fixes for glvis-js
  lib/aux_js.cpp
Labels: WIP, JS

#309 Fixed Shift combinations with different keyboard layouts
  lib/sdl.cpp
Labels: bug
